project_id = "txngdosfbiixmypksldr"

[functions.chat-ai]
verify_jwt = false

[functions.erp-api-tester]
verify_jwt = true

[functions.erp-data-uploader]
verify_jwt = true

[functions.notification-handler]
verify_jwt = false

[functions.sync-to-github]
verify_jwt = false
