project_id = "bxyoirmvxugbfyxhlfaf"

[functions.federated-agent]
verify_jwt = false

[functions.success-story-agent]
verify_jwt = false

[functions.fundamentos-agent]
verify_jwt = false

[functions.catalogo-datos-agent]
verify_jwt = false

[functions.flujo-3-actores-agent]
verify_jwt = false

[functions.politicas-odrl-agent]
verify_jwt = false

[functions.web3-dids-agent]
verify_jwt = false

[functions.ia-conversacional-agent]
verify_jwt = false

[functions.conectores-erp-agent]
verify_jwt = false

[functions.red-gaia-x-agent]
verify_jwt = false